### ISSUE TITLE
`define()` undefined

### ISSUE THREAD

**Issue by jamesdixon** [bkeepers/rosie#38]
Hi,

I'm attempting to use Rosie and running into the following error:

```
Factory.define('User', User)
        ^
TypeError: undefined is not a function
    at Object.<anonymous> (/Users/jamesdixon/Projects/scout/platform/test/index.js:13:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

The code is as follows:

```javascript
var Factory = require('rosie');

var User = function () {
  return {
    firstName: '',
    lastName: '',
    email: '',
    password: '',
    active: false
  };
};

Factory.define('User', User)
  .sequence('id')
  .attr('firstName', 'john')
  .attr('lastName', 'doe')
  .sequence('email', function(i) {
    return 'test_' + i + '@gmail.com';
  })
  .attr('password', '12345678')
  .attr('active', true);
```

I'm running node 0.12.2 and running the file via `node index.js`. 

Any suggestions?

Best,
James

**Comment by eventualbuddha** [comment]
```js
var Factory = require('rosie').Factory;
```

**Comment by jamesdixon** [comment]
Thanks @eventualbuddha. For newbies like me, it may be good to have that as part of the example to avoid any confusion. Thanks again!

**Comment by eventualbuddha** [comment]
@jamesdixon I just today added some docs for exactly that: https://github.com/bkeepers/rosie#nodejs
